name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: clang
          - os: ubuntu-latest
            cc: gcc
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe"
        sudo apt-get update -y -qq
        sudo apt-get install meson ninja-build

    - name: Execute build
      env:
        CC: ${{ matrix.cc }}
      run: |
        meson setup build
        cd build && ninja
